### PR TITLE
ploigos-tool-zap - init add

### PR DESCRIPTION
**Pull request by InfoSec812**
#### What is this PR About?

Adds new containerfiles and supporting scripts to create a ploigos integrated container for [Zed Attack Proxy](https://owasp.org/www-project-zap/)

### CODE REVIEW

**Comment by itewk** [comment]
@InfoSec812 have you used this in a workflow yet to verify it works the way you want? if so, can you squash down your commits and then we will merge to main?

**Comment by InfoSec812** [comment]
No, I have not had the opportunity to try it and probably will not have time in the near future.

**Comment by itewk** [comment]
@BillBensing do you have someone to continue this work forward?

**Comment by dwinchell** [comment]
I am closing this as stale. Anyone who wants to work on it, please feel free to reopen it.

**Pull request closed without merging**
